import { IconType } from "react-icons";
import {
  FaArrowCircleDown,
  FaHtml5,
  FaJava,
  FaReact,
  FaEnvelope,
  FaPaperPlane,
  FaGithub,
  FaLinkedinIn,
  FaVuejs,
  FaGitAlt,
  FaFigma,
  FaBars,
  FaChevronRight,
  FaChevronDown,
  FaLink,
  FaChevronLeft,
  FaDocker,
} from "react-icons/fa";
import { IoLogoCss3, IoMdConstruct, IoMdPause } from "react-icons/io";
import {
  SiJavascript,
  SiTypescript,
  SiSass,
  SiPython,
  SiAngular,
  SiC,
  SiCplusplus,
  SiPhp,
  SiMysql,
  SiMongodb,
  SiExpress,
  SiNodedotjs,
  SiNextdotjs,
  SiNuxtdotjs,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiAdobepremierepro,
  SiBlender,
  SiIntellijidea,
  SiTailwindcss,
  SiKubernetes,
} from "react-icons/si";
import { VscDebugBreakpointData } from "react-icons/vsc";
import { GrStatusUnknown } from "react-icons/gr";
import { BsFillCalendarCheckFill, BsFillTerminalFill, BsXLg } from "react-icons/bs";
import { ImCheckmark } from "react-icons/im";
import { BiLinkExternal } from "react-icons/bi";

const icons = new Map<string, IconType>([
  ["externalLink", BiLinkExternal],
  ["link", FaLink],
  ["Completed", ImCheckmark],
  ["In Development", IoMdConstruct],
  ["On Hold", IoMdPause],
  ["Cancelled", BsXLg],
  ["Planned", BsFillCalendarCheckFill],
  ["open", FaBars],
  ["close", BsXLg],
  ["arrowCircleDown", FaArrowCircleDown],
  ["empty", VscDebugBreakpointData],
  ["email", FaEnvelope],
  ["send", FaPaperPlane],
  ["github", FaGithub],
  ["git", FaGitAlt],
  ["loadMore", FaChevronDown],
  ["linkedin", FaLinkedinIn],
  ["arrowRight", FaChevronRight],
  ["arrowLeft", FaChevronLeft],
  ["html", FaHtml5],
  ["css", IoLogoCss3],
  ["js", SiJavascript],
  ["ts", SiTypescript],
  ["react", FaReact],
  ["angular", SiAngular],
  ["java", FaJava],
  ["vue", FaVuejs],
  ["sass", SiSass],
  ["python", SiPython],
  ["c", SiC],
  ["c++", SiCplusplus],
  ["php", SiPhp],
  ["mysql", SiMysql],
  ["mongodb", SiMongodb],
  ["express", SiExpress],
  ["nodeJs", SiNodedotjs],
  ["nextJs", SiNextdotjs],
  ["nuxtJs", SiNuxtdotjs],
  ["intellij", SiIntellijidea],
  ["photoshop", SiAdobephotoshop],
  ["illustrator", SiAdobeillustrator],
  ["premierePro", SiAdobepremierepro],
  ["figma", FaFigma],
  ["blender", SiBlender],
  ["terminal", BsFillTerminalFill],
  ["tailwind", SiTailwindcss],
  ["docker", FaDocker],
  ["kubernetes", SiKubernetes],
]);

export const getIcon = (name: string) => {
  return icons.get(name) || GrStatusUnknown;
};
