import { IconType } from "react-icons";
import {
  FaHtml5,
  FaJava,
  FaReact,
  FaVuejs,
  FaDocker,
  FaChevronLeft,
  FaChevronRight,
  FaGitAlt,
  FaGithub,
  FaEnvelope,
  FaLink,
  FaBars,
  FaArrowCircleDown,
  FaPaperPlane,
  FaChevronDown,
  FaLinkedinIn,
  FaAws,
} from "react-icons/fa";
import { IoLogoCss3, IoMdConstruct, IoMdPause } from "react-icons/io";
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiC,
  SiCplusplus,
  SiExpress,
  SiNextdotjs,
  SiNuxtdotjs,
  SiTailwindcss,
  SiGo,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiFastapi,
  SiSvelte,
  SiKubernetes,
  SiGithubactions,
  SiTerraform,
} from "react-icons/si";
import { DiRedis } from "react-icons/di";
import { GrStatusUnknown } from "react-icons/gr";
import { BiLinkExternal } from "react-icons/bi";
import { ImCheckmark } from "react-icons/im";
import { BsXLg, BsFillCalendarCheckFill } from "react-icons/bs";
import { VscDebugBreakpointData } from "react-icons/vsc";

const icons = new Map<string, IconType>([
  ["externalLink", BiLinkExternal],
  ["link", FaLink],
  ["Completed", ImCheckmark],
  ["In Development", IoMdConstruct],
  ["On Hold", IoMdPause],
  ["Cancelled", BsXLg],
  ["Planned", BsFillCalendarCheckFill],
  ["open", FaBars],
  ["close", BsXLg],
  ["arrowCircleDown", FaArrowCircleDown],
  ["empty", VscDebugBreakpointData],
  ["email", FaEnvelope],
  ["send", FaPaperPlane],
  ["github", FaGithub],
  ["git", FaGitAlt],
  ["loadMore", FaChevronDown],
  ["linkedin", FaLinkedinIn],
  ["arrowRight", FaChevronRight],
  ["arrowLeft", FaChevronLeft],
  ["html", FaHtml5],
  ["css", IoLogoCss3],
  ["js", SiJavascript],
  ["ts", SiTypescript],
  ["react", FaReact],
  ["java", FaJava],
  ["vue", FaVuejs],
  ["python", SiPython],
  ["c", SiC],
  ["c++", SiCplusplus],
  ["go", SiGo],
  ["express", SiExpress],
  ["nextJs", SiNextdotjs],
  ["nuxtJs", SiNuxtdotjs],
  ["tailwind", SiTailwindcss],
  ["docker", FaDocker],
  ["postgres", SiPostgresql],
  ["mysql", SiMysql],
  ["mongodb", SiMongodb],
  ["redis", DiRedis],
  ["fastapi", SiFastapi],
  ["svelte", SiSvelte],
  ["mongo", SiMongodb],
  ["mysql", SiMysql],
  ["postgres", SiPostgresql],
  ["kubernetes", SiKubernetes],
  ["githubActions", SiGithubactions],
  ["terraform", SiTerraform],
  ["aws", FaAws],
]);

export const getIcon = (name: string) => {
  return icons.get(name) || GrStatusUnknown;
};
