import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Header from "../components/Header/Header";
import HomeLanding from "../components/HomeLanding";
import Section from "../components/Section";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Borhan Saflo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <HomeLanding />
        <Section />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
